version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: literatureEngineDB
    restart: unless-stopped
    ports:
      - "8001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: